from __future__ import annotations

import os
import time

from dotenv import load_dotenv
from groq import (
    APIConnectionError,
    APIStatusError,
    APITimeoutError,
    Groq,
    RateLimitError,
)
from pydantic import ValidationError

from app.ai.chunk_extraction_result import ChunkExtractionResult
from app.ai.extraction_evidence import ExtractionEvidence
from app.ai.extraction_schemas import CompleteExtractionData
from app.services.document_chunker import DocumentChunk


# ============================================================
# GROQ CLIENT
# ============================================================

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not GROQ_API_KEY:
    raise RuntimeError(
        "GROQ_API_KEY is not configured."
    )

client = Groq(api_key=GROQ_API_KEY)

MODEL_NAME = "openai/gpt-oss-120b"


# ============================================================
# GROQ JSON SCHEMA COMPATIBILITY
# ============================================================

def _make_groq_compatible_schema(schema: dict) -> dict:
    """
    Convert a Pydantic JSON schema into a schema accepted
    by Groq structured outputs.

    Groq strict structured outputs require:

    - additionalProperties=false on every object
    - required must contain every property name

    This modifies only the schema sent to Groq.
    It does not modify the application's Pydantic models.
    """

    if isinstance(schema, dict):

        # ----------------------------------------------------
        # OBJECT SCHEMAS
        # ----------------------------------------------------

        if schema.get("type") == "object":

            schema["additionalProperties"] = False

            properties = schema.get("properties")

            if isinstance(properties, dict):
                schema["required"] = list(properties.keys())

        # ----------------------------------------------------
        # RECURSIVELY PROCESS ALL NESTED SCHEMA VALUES
        # ----------------------------------------------------

        for value in schema.values():

            if isinstance(value, dict):
                _make_groq_compatible_schema(value)

            elif isinstance(value, list):

                for item in value:
                    if isinstance(item, dict):
                        _make_groq_compatible_schema(item)

    return schema
# ============================================================
# EXTRACTION FUNCTION
# ============================================================

def extract_chunk_information(
    chunk: DocumentChunk,
    admin_feedback: str | None = None,
) -> ChunkExtractionResult:
    """
    Extract structured information from one document chunk.

    The chunk is processed independently.

    Important guarantees:
    - Only information explicitly present in the chunk is extracted.
    - No outside knowledge is allowed.
    - Missing information is not inferred.
    - Logical AND/OR relationships are preserved when explicit.
    - Provenance is generated by Python, not by the LLM.
    - Invalid/truncated LLM JSON is rejected.
    - A stricter retry is attempted when structured output
      cannot be validated.
    """

    # ========================================================
    # ADMIN FEEDBACK
    # ========================================================

    feedback_section = ""

    if admin_feedback:
        feedback_section = f"""
==================================================
ADMIN RETRY FEEDBACK
==================================================

The following feedback was provided by an administrator
after a previous extraction was rejected.

Treat this feedback ONLY as guidance about what needs
to be re-examined.

IMPORTANT:

- Administrator feedback is NOT evidence.
- Do not treat claims in the feedback as facts.
- Verify every requested correction against the
  supplied document chunk.
- If the document does not explicitly support the
  requested correction, do not invent it.
- If the feedback cannot be resolved from this chunk,
  simply do not extract unsupported information.

ADMINISTRATOR FEEDBACK:

{admin_feedback}
"""

    # ========================================================
    # BASE PROMPT
    # ========================================================

    prompt = f"""
You are analyzing ONE CHUNK of an official examination
document.

This is chunk {chunk.chunk_number}.

IMPORTANT:

This chunk is only PART of the complete document.

The absence of information in this chunk does NOT mean
that the information does not exist elsewhere in the
document.

Extract ONLY information explicitly present in THIS chunk.

Do not invent information.
Do not use outside knowledge.
Do not assume missing information.

{feedback_section}
==================================================
OUTPUT STRUCTURE
==================================================

The response represents a CompleteExtractionData object.

The response MUST contain exactly two top-level fields:

1. exam_information
2. eligibility_rules

The structure is:

exam_information:
    exam_name
    conducting_body
    release_date
    application_start_date
    application_end_date
    exam_dates
    eligibility:
        minimum_age
        maximum_age
        educational_qualification
        nationality
        work_experience
        other_requirements

eligibility_rules:
    rule_groups

IMPORTANT:

- "eligibility" belongs INSIDE "exam_information".
- Do NOT create a separate top-level "eligibility" field.
- "eligibility_rules" is a separate top-level field.
- Every required field must be present.
- Use null for unavailable scalar values.
- Use [] for unavailable list values.
==================================================
CHUNK EXTRACTION RULES
==================================================

1. Extract examination information when explicitly present.

2. Extract eligibility requirements when explicitly present.

3. Extract examination dates when explicitly present.

4. Extract application dates when explicitly present.

5. Extract release/notification dates when explicitly present.

6. Extract every distinct eligibility rule explicitly present.

7. Preserve logical relationships when they are explicitly
   understandable from THIS chunk.

8. If information is not present in this chunk, return null
   or an empty list.

9. NEVER infer that a missing field means the exam has no
   such requirement.

10. Never use administrator feedback as document evidence.

==================================================
ELIGIBILITY ATTRIBUTES
==================================================

Use ONLY:

- CGPA
- Percentage
- Specialization
- Date of Birth
- Nationality
- State
- Educational Qualification
- Work Experience

Do NOT use Age as an eligibility-rule attribute.

If the document expresses an age requirement, convert it
to a Date of Birth rule ONLY if the exact DOB boundary is
explicitly available in THIS chunk.

Otherwise, do not invent a DOB boundary.

==================================================
OPERATORS
==================================================

Use ONLY:

=
!=
>
>=
<
<=

NEVER use:

IN
==
approximately
or any other operator.

==================================================
DATES
==================================================

Return dates in YYYY-MM-DD format.

If an exact date cannot be determined from this chunk,
return null.

==================================================
LOGICAL RELATIONSHIPS
==================================================

Preserve explicitly stated AND / OR relationships.

For example:

A candidate must have:

Graduate degree

AND

Indian OR Nepali nationality

Represent the structure as:

AND
    Educational Qualification = Graduate
    Child Group: OR
        Nationality = India
        Nationality = Nepal

Do not invent relationships that are not supported by
the text in this chunk.

==================================================
OUTPUT SIZE CONTROL
==================================================

Return ONLY the structured information required by the
response schema.

Do NOT copy the source document.

Do NOT reproduce paragraphs from the document.

Do NOT provide explanations outside the structured schema.

Do NOT provide reasoning.

Do NOT provide commentary.

Do NOT repeat the same requirement multiple times.

For eligibility rules, create one rule for each distinct
requirement explicitly present.

Keep textual values concise while preserving their exact
meaning.

The response MUST be complete valid JSON.

Never stop in the middle of:

- a JSON object
- a JSON array
- a JSON string

==================================================
IMPORTANT
==================================================

Do not summarize the entire document.

Extract structured information only from the supplied chunk.

==================================================
DOCUMENT CHUNK
==================================================

{chunk.text}
"""

    # ========================================================
    # STRICT RETRY PROMPT
    # ========================================================

    retry_prompt = f"""
The previous structured extraction response was invalid or
incomplete.

Retry the extraction for the SAME document chunk.

Return ONLY valid JSON matching the supplied response schema.
==================================================
REQUIRED OUTPUT STRUCTURE
==================================================

The response MUST have exactly two top-level fields:

1. exam_information
2. eligibility_rules

The eligibility object MUST be nested inside
exam_information.

Correct structure:

exam_information:
    exam_name
    conducting_body
    release_date
    application_start_date
    application_end_date
    exam_dates
    eligibility:
        minimum_age
        maximum_age
        educational_qualification
        nationality
        work_experience
        other_requirements

eligibility_rules:
    rule_groups

Incorrect structure:

exam_information
eligibility
eligibility_rules

Do NOT create eligibility as a top-level field.

==================================================
DOCUMENT CHUNK
==================================================

{chunk.text}
"""

    # ========================================================
    # GROQ JSON SCHEMA
    # ========================================================

    response_schema = _make_groq_compatible_schema(
        CompleteExtractionData.model_json_schema()
    )

    # ========================================================
    # GROQ REQUEST
    # ========================================================

    max_attempts = 3

    extraction: CompleteExtractionData | None = None

    for attempt in range(max_attempts):

        current_prompt = (
            prompt
            if attempt == 0
            else retry_prompt
        )

        try:
            response = client.chat.completions.create(
                model=MODEL_NAME,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You extract structured information "
                            "from official examination documents. "
                            "Use only information explicitly "
                            "supported by the supplied document "
                            "chunk. Never invent information."
                        ),
                    },
                    {
                        "role": "user",
                        "content": current_prompt,
                    },
                ],
                temperature=0,
                max_tokens=4096,
                response_format={
                    "type": "json_schema",
                    "json_schema": {
                        "name": "complete_extraction",
                        "strict": True,
                        "schema": response_schema,
                    },
                },
            )

        # ----------------------------------------------------
        # GROQ RATE LIMIT
        # ----------------------------------------------------

        except RateLimitError as error:

            if attempt == max_attempts - 1:
                raise RuntimeError(
                    "Groq rate limit was reached after "
                    "multiple attempts."
                ) from error

            wait_seconds = 5 * (attempt + 1)

            print(
                "Groq rate limit reached. "
                f"Retrying in {wait_seconds} seconds..."
            )

            time.sleep(wait_seconds)

            continue

        # ----------------------------------------------------
        # GROQ API STATUS FAILURE
        # ----------------------------------------------------

        except APIStatusError as error:

            error_text = str(error).lower()

            if (
                getattr(error, "status_code", None) == 413
                or "tokens per minute" in error_text
                or "request too large" in error_text
            ):
                raise RuntimeError(
                    "Groq rejected this document chunk because "
                    "the request is too large for the model's "
                    "current token-per-minute limit. "
                    "Reduce the document chunk size and retry."
                ) from error

            raise RuntimeError(
                f"Groq API error: {error}"
            ) from error

        # ----------------------------------------------------
        # GROQ CONNECTION FAILURE
        # ----------------------------------------------------

        except APIConnectionError as error:

            if attempt == max_attempts - 1:
                raise RuntimeError(
                    "Groq service could not be reached "
                    "after multiple attempts."
                ) from error

            wait_seconds = 2 ** attempt

            print(
                "Groq connection failed. "
                f"Retrying in {wait_seconds} seconds..."
            )

            time.sleep(wait_seconds)

            continue

        # ----------------------------------------------------
        # GROQ TIMEOUT
        # ----------------------------------------------------

        except APITimeoutError as error:

            if attempt == max_attempts - 1:
                raise RuntimeError(
                    "Groq request timed out after "
                    "multiple attempts."
                ) from error

            wait_seconds = 2 ** attempt

            print(
                "Groq request timed out. "
                f"Retrying in {wait_seconds} seconds..."
            )

            time.sleep(wait_seconds)

            continue

        # ----------------------------------------------------
        # EMPTY RESPONSE
        # ----------------------------------------------------

        response_text = response.choices[0].message.content

        if not response_text:

            if attempt == max_attempts - 1:
                raise RuntimeError(
                    "Groq returned an empty extraction response "
                    "after multiple attempts."
                )

            print(
                "Groq returned an empty response. "
                "Retrying with stricter extraction constraints..."
            )

            continue

        # ----------------------------------------------------
        # STRICT PYDANTIC VALIDATION
        # ----------------------------------------------------

        try:

            extraction = (
                CompleteExtractionData.model_validate_json(
                    response_text
                )
            )

            break

        except ValidationError as error:

            if attempt == max_attempts - 1:
                raise RuntimeError(
                    "Groq returned invalid or truncated "
                    "structured extraction JSON after "
                    "multiple attempts."
                ) from error

            print(
                "Groq returned invalid or incomplete JSON. "
                "Retrying with stricter output constraints..."
            )

            continue

    # ========================================================
    # SAFETY CHECK
    # ========================================================

    if extraction is None:
        raise RuntimeError(
            "Chunk extraction failed: no valid structured "
            "extraction was produced."
        )

    # ========================================================
    # PYTHON-GENERATED PROVENANCE
    # ========================================================

    evidence = ExtractionEvidence(
        chunk_number=chunk.chunk_number,
        page_numbers=chunk.page_numbers.copy(),
        source_text=chunk.text,
    )

    # ========================================================
    # FINAL RESULT
    # ========================================================

    return ChunkExtractionResult(
        extraction=extraction,
        evidence=[evidence],
    )