from __future__ import annotations

import os

from dotenv import load_dotenv
from google import genai

from app.ai.chunk_extraction_result import ChunkExtractionResult
from app.ai.extraction_evidence import ExtractionEvidence
from app.ai.extraction_schemas import CompleteExtractionData
from app.services.document_chunker import DocumentChunk


load_dotenv()


client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)


def extract_chunk_information(
    chunk: DocumentChunk,
) -> ChunkExtractionResult:
    """
    Extract structured information from one document chunk.

    Provenance is NOT generated by the LLM.

    It is attached directly from the DocumentChunk object so that
    chunk number, page numbers, and source text remain trustworthy.
    """

    prompt = f"""
You are analyzing ONE CHUNK of an official examination document.

This is chunk {chunk.chunk_number}.

IMPORTANT:

This chunk is only PART of the complete document.

The absence of information in this chunk does NOT mean
that the information does not exist elsewhere in the document.

Extract ONLY information explicitly present in THIS chunk.

Do not invent information.
Do not use outside knowledge.
Do not assume missing information.

==================================================
CHUNK EXTRACTION RULES
==================================================

1. Extract examination information when explicitly present.
2. Extract eligibility requirements when explicitly present.
3. Extract examination dates when explicitly present.
4. Extract application dates when explicitly present.
5. Extract release/notification dates when explicitly present.
6. Extract every eligibility rule explicitly present.
7. Preserve logical relationships when they are explicitly
   understandable from THIS chunk.
8. If information is not present in this chunk, return null
   or an empty list.
9. NEVER infer that a missing field means the exam has no
   such requirement.

==================================================
ELIGIBILITY ATTRIBUTES
==================================================

Use ONLY:

- CGPA
- Percentage
- Specialization
- Date of Birth
- Nationality
- State
- Educational Qualification
- Work Experience

Do NOT use Age as an eligibility-rule attribute.

If the document expresses an age requirement, convert it
to a Date of Birth rule ONLY if the exact DOB boundary is
explicitly available in THIS chunk.

Otherwise, do not invent a DOB boundary.

==================================================
OPERATORS
==================================================

Use ONLY:

=
!=
>
>=
<
<=

NEVER use:

IN
==
approximately
or any other operator.

==================================================
DATES
==================================================

Return dates in YYYY-MM-DD format.

If an exact date cannot be determined from this chunk,
return null.

==================================================
LOGICAL RELATIONSHIPS
==================================================

Preserve explicitly stated AND / OR relationships.

For example:

A candidate must have:

Graduate degree

AND

Indian OR Nepali nationality

Represent the structure as:

AND
    Educational Qualification = Graduate

    Child Group: OR
        Nationality = India
        Nationality = Nepal

Do not invent relationships that are not supported by
the text in this chunk.

==================================================
IMPORTANT
==================================================

Do not summarize the entire document.

Extract structured information only from the supplied chunk.

==================================================
DOCUMENT CHUNK
==================================================

{chunk.text}
"""

    response = client.models.generate_content(
        model="gemini-3.5-flash",
        contents=prompt,
        config={
            "response_mime_type": "application/json",
            "response_schema": CompleteExtractionData,
        },
    )

    extraction = CompleteExtractionData.model_validate_json(
        response.text
    )

    evidence = ExtractionEvidence(
        chunk_number=chunk.chunk_number,
        page_numbers=chunk.page_numbers.copy(),
        source_text=chunk.text,
    )

    return ChunkExtractionResult(
        extraction=extraction,
        evidence=[evidence],
    )