// Mock dataset standing in for Vivek's API during frontend development.
// Shape matches what the backend is expected to return, so wiring up the
// real endpoints later should mean deleting the mock bodies in api/*.js,
// not reshaping the components that consume them.

export const mockExams = [
  {
    id: "gate-2027",
    name: "GATE",
    organization: "IISc / IIT consortium",
    category: "Postgraduate entrance",
    applicationStart: "2026-08-24",
    applicationDeadline: "2026-10-03",
    examDate: "2027-02-07",
    eligibilityRule: "Final-year or completed B.E./B.Tech/B.Sc in an eligible discipline.",
    syllabus: ["Engineering Mathematics", "Core discipline subjects", "General Aptitude"],
    importantInfo: [
      "Multiple exam sessions across subjects — check your discipline's date.",
      "Valid GATE score is required for most IIT/IISc M.Tech admissions.",
    ],
    officialLink: "https://gate.iitk.ac.in",
  },
  {
    id: "cat-2026",
    name: "CAT",
    organization: "IIM consortium",
    category: "Management entrance",
    applicationStart: "2026-08-01",
    applicationDeadline: "2026-09-20",
    examDate: "2026-11-29",
    eligibilityRule: "Bachelor's degree with at least 50% marks (45% for reserved categories).",
    syllabus: ["Verbal Ability & Reading Comprehension", "Data Interpretation & Logical Reasoning", "Quantitative Ability"],
    importantInfo: ["Final-year students can apply provisionally.", "Score is accepted by 1000+ B-schools beyond the IIMs."],
    officialLink: "https://iimcat.ac.in",
  },
  {
    id: "gre-general",
    name: "GRE General Test",
    organization: "ETS",
    category: "Study abroad — Master's/PhD",
    applicationStart: "2026-01-01",
    applicationDeadline: "2026-12-31",
    examDate: "Rolling — book any date",
    eligibilityRule: "No fixed eligibility; typically taken by students applying to Master's/PhD programs abroad.",
    syllabus: ["Verbal Reasoning", "Quantitative Reasoning", "Analytical Writing"],
    importantInfo: ["Scores are valid for 5 years.", "Can be taken at home or at a test center."],
    officialLink: "https://ets.org/gre",
  },
  {
    id: "upsc-cse-2027",
    name: "UPSC Civil Services",
    organization: "Union Public Service Commission",
    category: "Government / Civil services",
    applicationStart: "2027-02-05",
    applicationDeadline: "2027-02-25",
    examDate: "2027-05-23",
    eligibilityRule: "Bachelor's degree in any discipline from a recognized university.",
    syllabus: ["General Studies I–IV", "Optional Subject", "Essay", "CSAT"],
    importantInfo: ["Age limit and attempt count vary by category.", "Prelims, Mains, and Interview across ~10 months."],
    officialLink: "https://upsc.gov.in",
  },
  {
    id: "nda-2027",
    name: "NDA",
    organization: "Union Public Service Commission",
    category: "Defence entrance",
    applicationStart: "2026-12-20",
    applicationDeadline: "2027-01-10",
    examDate: "2027-04-18",
    eligibilityRule: "12th pass, unmarried male/female candidates within the specified age band.",
    syllabus: ["Mathematics", "General Ability Test"],
    importantInfo: ["Followed by SSB interview.", "Not applicable to candidates who already hold a bachelor's degree."],
    officialLink: "https://upsc.gov.in",
  },
  {
    id: "clat-pg-2027",
    name: "CLAT PG",
    organization: "Consortium of NLUs",
    category: "Law postgraduate entrance",
    applicationStart: "2026-07-15",
    applicationDeadline: "2026-11-17",
    examDate: "2026-12-07",
    eligibilityRule: "LL.B. degree (or final year) with minimum 50% aggregate.",
    syllabus: ["Constitutional Law", "Jurisprudence", "Other law subjects"],
    importantInfo: ["Common entrance for LL.M. across 20+ NLUs."],
    officialLink: "https://consortiumofnlus.ac.in",
  },
];

export const mockNotifications = [
  {
    id: "n1",
    type: "new-eligible",
    title: "You're now eligible for CAT 2026",
    message: "Your updated CGPA meets the eligibility threshold for CAT 2026.",
    examId: "cat-2026",
    read: false,
    timestamp: "2026-08-27T09:15:00+05:30",
  },
  {
    id: "n2",
    type: "deadline",
    title: "GATE application closes in 10 days",
    message: "Applications for GATE 2027 close on 3 Oct 2026.",
    examId: "gate-2027",
    read: false,
    timestamp: "2026-08-26T18:00:00+05:30",
  },
  {
    id: "n3",
    type: "exam",
    title: "CLAT PG exam date announced",
    message: "CLAT PG 2027 will be held on 7 Dec 2026.",
    examId: "clat-pg-2027",
    read: true,
    timestamp: "2026-08-20T11:30:00+05:30",
  },
  {
    id: "n4",
    type: "update",
    title: "GRE eligibility notes updated",
    message: "ETS clarified score validity is 5 years, updated on the exam's details page.",
    examId: "gre-general",
    read: true,
    timestamp: "2026-08-14T08:00:00+05:30",
  },
];

export const mockProfile = {
  name: "Ananya Rao",
  dob: "2004-03-12",
  nationality: "Indian",
  state: "Karnataka",
  college: "PES University",
  branch: "Computer Science and Engineering",
  yearOfStudy: "4th Year",
  cgpa: "8.7",
  percentage: "",
  workExperience: [],
  qualifications: [
    { level: "12th / Senior Secondary", institution: "Sri Kumaran's PU College", field: "PCM", yearCompleted: "2022", score: "94%" },
  ],
  hasHigherQualification: false,
  previousQualification: null,
};
