"""initial schema

Revision ID: a92cf1bef6f6
Revises: 
Create Date: 2026-09-30 11:29:20.396923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92cf1bef6f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eligibilityrulegroup', sa.Column('parent_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eligibilityrulegroup', 'eligibilityrulegroup', ['parent_group_id'], ['group_id'])
    op.alter_column('officialnotification', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('officialnotification', 'document_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # op.drop_column('officialnotification', 'exam_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officialnotification', sa.Column('exam_date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('officialnotification', 'document_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('officialnotification', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'eligibilityrulegroup', type_='foreignkey')
    op.drop_column('eligibilityrulegroup', 'parent_group_id')
    # ### end Alembic commands ###
